### ISSUE TITLE
please report it to the author of the 'ampere_storage_pro_modbus' custom integration

### ISSUE THREAD

**Issue by UDicke** [dboeni/home-assistant-ampere-storage-pro-modbus#1]
Logger: homeassistant.helpers.typing
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 15:31:24 (1 Vorkommnisse)
Zuletzt protokolliert: 15:31:24

HomeAssistantType was used from ampere_storage_pro_modbus, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'ampere_storage_pro_modbus' custom integration

@dboeni Thank you for that integration! 👍

**Comment by dboeni** [comment]
Thank you for this information. I will fix this in the next version.
