### ISSUE TITLE
please provide a more detailed description for updating to Version 0.2.0

### ISSUE THREAD

**Issue by UDicke** [dboeni/home-assistant-ampere-storage-pro-modbus#5]
```
With this version, all devices must be set up again as the domain of this integration has been changed.

Please delete the old device first and then create a new one. All historical data will then be available if the same name is selected for the device.
```
Leider bin ich mit dieser Beschreibung etwas unsicher was genau wie zu machen ist und bevor bei mir vieles nicht mehr geht und ich evtl. auch noch die Historie zerschieße, frag ich lieber.

Unfortunately, with this description I'm a bit unsure about exactly how to do it and before things stop working for me and I end up destroying the history, I'd rather ask.

**Comment by dboeni** [comment]
Kein Problem.
Ich erstelle Mal eine Bildliche Anleitung 

No problem.
I'll create a pictorial guide.

**Comment by dboeni** [comment]
Illustrated instructions for the update to version v0.2.0

**Precondition**
 - An inverter is set up (eg. `Ampere.StoragePro Test`)
 - Installed version < v0.2.0

**Update process**
 1. Accept the update and then restart home assistant
![grafik](https://github.com/user-attachments/assets/73b031ce-14df-4b61-a8ce-e86a9ed4921c)
 2. Now comes a repair message. First ignore it and don't confirm anything
![grafik](https://github.com/user-attachments/assets/8375381c-94d0-4d1b-bbf8-23e30f69d599)
 3. Now go to the old integration under Settings > Device & services ...
![grafik](https://github.com/user-attachments/assets/6cf80413-d1b4-445e-8a0a-b502cff639c3)
 4. ...and delete the configured inverter
![grafik](https://github.com/user-attachments/assets/6a7a2221-0477-4791-8bf3-f40572d88e8b)
 5. Now set up the inverter via “Add integration”.
**Important: Use the same name as the old inverter set up**
![grafik](https://github.com/user-attachments/assets/81c21f68-c24f-439b-afb7-b7750ce4623c)
 6. Current presentation of the integrations
![grafik](https://github.com/user-attachments/assets/ab077c5d-0ce1-4c14-8c6f-7c80a0c2ef86)
 7. Now you can confirm the repair message with “Remove previous configurations”
![grafik](https://github.com/user-attachments/assets/e28b67bb-9988-442f-9280-7ad083c501d1)
 8. The notification with “Invalid config” can be dismissed
 
![grafik](https://github.com/user-attachments/assets/2e9b6176-0862-4cd4-942a-896a645d1b29)

 9. Finish

**Comment by UDicke** [comment]
Danke! Installation war erfolgreich, auch wenn ich keine Fehlermeldungen hatte. (Punkt 2, bei mir lief die alte Version einfach weiter)
Nach dem Löschen vom alten Device und bei der Neukonfiguration habe ich leider den falschen Namen eingegeben und musste die Prozedur nochmal wiederholen.
Der neu einzugebende Name ist nicht der
![grafik](https://github.com/user-attachments/assets/f734a2be-bf94-4a4c-bd03-cad987a45c30)
sondern der Prefix vor den Entity Namen vor dem 1, "_". Bei mir
![grafik](https://github.com/user-attachments/assets/250ddca3-4a93-46d5-a9e2-bb1115af446f)
nach Neustart lief alles wie erwartet!
Vielen Dank für die detailierte Beschreibung!
